/*SELECT t1.Y,t1.M,t1.shopid,t1.ertrag,t2.EDIT_TIME FROM 
	(SELECT YEAR(datum) AS Y,MONTH(datum) AS M,shopid,haendlername,sum(ertrag) AS ertrag FROM kunden_bestellungen 
	WHERE (datum BETWEEN '2016-12-01' AND '2017-01-31')
	GROUP BY YEAR(datum),MONTH(datum),shopid) t1
INNER JOIN 
	SELECT t2.Y,t2.M,t2.SHOP_ID,SUM(t2.EDIT_TIME) AS EDIT_TIME,COUNT(t2.TICKET_ID) AS CNT,t2.S FROM 
		(SELECT YEAR(DATE(RECEIVE_DATE)) AS Y,MONTH(DATE(RECEIVE_DATE)) AS M,SHOP_ID,EDIT_TIME_IN_MS AS EDIT_TIME, "KS" AS S, TICKET_ID 
		FROM ks_eingang 
		WHERE (DATE(RECEIVE_DATE) BETWEEN '2016-12-01' AND '2017-01-31') 
		AND SHOP_ID <> 0 AND SHOP_ID IS NOT NULL
		UNION ALL 
		SELECT YEAR(DATE(RECEIVE_DATE)) AS Y,MONTH(DATE(RECEIVE_DATE)) AS M,SHOP_ID,EDIT_TIME_IN_MS AS EDIT_TIME, "HS" AS S, TICKET_ID 
		FROM hs_reporting 
		WHERE (DATE(RECEIVE_DATE) BETWEEN '2016-12-01' AND '2017-01-31') 
		AND SHOP_ID <> 0 AND SHOP_ID IS NOT NULL) t2
	GROUP BY t2.Y, t2.M, t2.S, t2.SHOP_ID;/*
ON t1.Y = t2.Y AND t1.M = t2.M AND t1.shopid = t2.SHOP_ID;*/