UPDATE kosten SET 
	tickets = 
	(SELECT COUNT(*) 
	FROM ks_eingang 
	WHERE MONTH(DATE(RECEIVE_DATE)) = 2 AND YEAR(DATE(RECEIVE_DATE)) = 2017),
	edit_time= 
	(SELECT SUM(EDIT_TIME_IN_MS) 
	FROM ks_eingang 
	WHERE MONTH(DATE(RECEIVE_DATE)) = 2 AND YEAR(DATE(RECEIVE_DATE)) = 2017) 
WHERE jahr = 2017 AND monat = 2 AND service = 'ks';