SELECT tN.SHOP_ID, COUNT(PROCESS_ID) FROM 
(
	SELECT SHOP_ID, PROCESS_ID
	FROM ks_eingang 
	WHERE (DATE(RECEIVE_DATE) BETWEEN '2016-12-01' AND '2017-01-31')
	UNION ALL 
	SELECT SHOP_ID, PROCESS_ID
	FROM hs_reporting 
	WHERE (DATE(RECEIVE_DATE) BETWEEN '2016-12-01' AND '2017-01-31')
) AS tN
GROUP BY tN.SHOP_ID 
HAVING tN.SHOP_ID <> 0 
ORDER BY COUNT(PROCESS_ID) DESC;